# This file was generated by GoReleaser. DO NOT EDIT.
cask "backscroll" do
  version "0.7.3"

  on_macos do
    on_intel do
      sha256 "4e851053e9a5655d8bc9b9376df5fbc627f7799dc5cb34c75d50a9fcde065327"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe462be34e8c46bf9cbd5c6fdb940328f82acc491e2560516c2adf3afb4a02ef"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "620c115bf2b420e9a9ca66a4c9ee50731255521b902873896c21723a0585b84a"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "85056c05012cbc8e211880476c79cfa1e74f7faa8bab0c74032e073c5a60f516"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_arm64.tar.gz"
    end
  end

  name "backscroll"
  desc "Never lose a command's output: per-command searchable terminal history"
  homepage "https://github.com/soren-achebe/backscroll"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backscroll"
  manpage "man/backscroll.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backscroll"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Enable shell integration by adding to your shell rc:
      eval "$(backscroll init bash)"   # or zsh / fish
    then start recorded sessions with:
      backscroll run
  EOS
end
