# This file was generated by GoReleaser. DO NOT EDIT.
cask "backscroll" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "80b7b53f87c2174fec48535d4f998953c96f84dfb0041557187ad92b27912fd0"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01489de5a63600144d7e68857903e12ec2ea334052a1570deef660b041e0e16f"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae6e7531649e5e81bb968b651dacd858f7fcfb3039c84d829f02e50a2ed1ff38"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aff72fbffbe32e8d0687a9423b8a84c7ed52ed9bdcf4acda77dfc27716239bcb"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_arm64.tar.gz"
    end
  end

  name "backscroll"
  desc "Never lose a command's output: per-command searchable terminal history"
  homepage "https://github.com/soren-achebe/backscroll"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backscroll"
  manpage "man/backscroll.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backscroll"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Enable shell integration by adding to your shell rc:
      eval "$(backscroll init bash)"   # or zsh / fish
    then start recorded sessions with:
      backscroll run
  EOS
end
