# This file was generated by GoReleaser. DO NOT EDIT.
cask "backscroll" do
  version "0.7.7"

  on_macos do
    on_intel do
      sha256 "5803477de04b7dfd0a0f7ccc7c3197ea4b1f446a9c688ee9c6400eec368bf104"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15962467ce6a6111dd6d534c1ccd079bcdb99c4722deea78510517bcbabfce25"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "646758876df34a775e522b04f2b7dae6eb1c0fa90615f002dd5019a012d15e95"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e28e5b6d7cf5e16404a2719102bac505bab4b485fa3492ce83c0ea545c51e6a8"
      url "https://github.com/soren-achebe/backscroll/releases/download/v#{version}/backscroll_linux_arm64.tar.gz"
    end
  end

  name "backscroll"
  desc "Never lose a command's output: per-command searchable terminal history"
  homepage "https://github.com/soren-achebe/backscroll"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backscroll"
  manpage "man/backscroll.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backscroll"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Enable shell integration by adding to your shell rc:
      eval "$(backscroll init bash)"   # or zsh / fish
    then start recorded sessions with:
      backscroll run
  EOS
end
